# Generated by Django 3.1.4 on 2020-12-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актёры и режиссёры', 'verbose_name_plural': 'Актёры и режиссёры'},
        ),
    ]
